### ISSUE TITLE
Please help me with installation of my proxon

### ISSUE THREAD

**Issue by AgentP38** [m4dmin/proxon-control#3]
Hi ,

vielen Dank, dass du mich unterstützen magst... Wie hast du das aufgebaut? über einen 2. Pi und MQTT?

**Comment by m4dmin** [comment]
Hi,
anfänglich habe ich tatsächlich mal mit einem Python Script gespielt, das die Kommunikation zu Home Assistant per MQTT hergestellt hat. Später ist mir dann aufgefallen, dass Home Assistant eine eigene Modbus Integration hat. Die nutze ich im Moment und es funktioniert problemlos und zuverlässig.
Mein Server auf dem Home Assistant läuft steht im Technikraum im Keller, wo auch meine Proxon Anlage steht. Ich musste also nur ein USB Verlängerungskabel kaufen um den [RS 485 Stick](https://www.amazon.de/gp/product/B081NBCJRS/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1) anzuschließen.

In den configuration.yaml Datei von Home Assistant habe ich dann folgende Zeile hinzugefügt:
```
# Modbus (Proxon) Konfiguration
modbus: !include modbus.yaml
```

Dann habe ich eine neue Datei "modbus.yaml" angelegt und wie folgt befüllt:
```
- name: proxon
  type: serial
  delay: 5
  baudrate: 19200
  bytesize: 8
  method: rtu
  parity: E
  port: /dev/ttyUSB0
  stopbits: 1
  switches:
    - name: "Heizelemente Global"
      unique_id: proxon_heizelemente_global
      scan_interval: 15
      slave: 41
      address: 325
      verify:
        delay: 1
    - name: "Heizelement Wohnzimmer (Zone1)"
      unique_id: proxon_heizelement_wohnzimmer_zone1
      scan_interval: 15
      slave: 41
      address: 187
      verify:
        delay: 1
    - name: "Heizelement Büro KG (Zone2)"
      unique_id: proxon_heizelement_buero_kg_zone2
      scan_interval: 15
      slave: 41
      address: 253
      verify:
        delay: 1
    - name: "Heizelement Küche"
      unique_id: proxon_heizelement_kueche
      scan_interval: 15
      slave: 41
      address: 254
      verify:
        delay: 1
    - name: "Heizelement Diele"
      unique_id: proxon_heizelement_diele
      scan_interval: 15
      slave: 41
      address: 255
      verify:
        delay: 1
    - name: "Heizelement Büro EG"
      unique_id: proxon_heizelement_buero_eg
      scan_interval: 15
      slave: 41
      address: 256
      verify:
        delay: 1
    - name: "Heizelement Schlafzimmer"
      unique_id: proxon_heizelement_schlafzimmer
      scan_interval: 15
      slave: 41
      address: 257
      verify:
        delay: 1
    - name: "Heizelement Martha"
      unique_id: proxon_heizelement_martha
      scan_interval: 15
      slave: 41
      address: 258
      verify:
        delay: 1
    - name: "Heizelement Marlene"
      unique_id: proxon_heizelement_marlene
      scan_interval: 15
      slave: 41
      address: 259
      verify:
        delay: 1
    - name: "Heizelement Keller 2"
      unique_id: proxon_heizelement_keller2
      scan_interval: 15
      slave: 41
      address: 261
      verify:
        delay: 1
    - name: "Heizelement Keller 3"
      unique_id: proxon_heizelement_keller3
      scan_interval: 15
      slave: 41
      address: 262
      verify:
        delay: 1
    - name: "Heizelement Wasser"
      unique_id: proxon_heizelement_wasser
      scan_interval: 15
      slave: 41
      address: 2001
      verify:
        delay: 1
    - name: "Kühlung Global"
      unique_id: proxon_kuehlung_global
      scan_interval: 15
      slave: 41
      address: 62
      verify:
        delay: 1
  sensors:
    - name: "Temperatur Wohnzimmer (Zone1)"
      unique_id: proxon_temperatur_wohnzimmer_zone1
      scan_interval: 30
      slave: 41
      address: 41
      input_type: input
      scale: 0.01
      precision: 1
      unit_of_measurement: °C
      data_type: uint16
    - name: "Temperatur Büro KG (Zone2)"
      unique_id: proxon_temperatur_buero_gg_zone2
      scan_interval: 30
      slave: 41
      address: 40
      input_type: input
      scale: 0.01
      precision: 1
      unit_of_measurement: °C
      data_type: uint16
    - name: "Temperatur Küche"
      unique_id: proxon_temperatur_kueche
      scan_interval: 30
      slave: 41
      address: 593
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Diele"
      unique_id: proxon_temperatur_diele
      scan_interval: 30
      slave: 41
      address: 596
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Büro EG"
      unique_id: proxon_temperatur_buero_eg
      scan_interval: 30
      slave: 41
      address: 599
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Schlafzimmer"
      unique_id: proxon_temperatur_schlafzimmer
      scan_interval: 30
      slave: 41
      address: 602
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Martha"
      unique_id: proxon_temperatur_martha
      scan_interval: 30
      slave: 41
      address: 605
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Marlene"
      unique_id: proxon_temperatur_marlene
      scan_interval: 30
      slave: 41
      address: 608
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Keller 2"
      unique_id: proxon_temperatur_keller2
      scan_interval: 30
      slave: 41
      address: 614
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Keller 3"
      unique_id: proxon_temperatur_keller3
      scan_interval: 30
      slave: 41
      address: 617
      input_type: input
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Temperatur Wasser"
      unique_id: proxon_temperatur_wasser
      scan_interval: 30
      slave: 41
      address: 814
      input_type: input
      scale: 0.1
      offset: -100
      precision: 1
      unit_of_measurement: °C
      data_type: uint16
    - name: "CO2 Wohnzimmer"
      unique_id: proxon_co2_wohnzimmer
      scan_interval: 30
      slave: 41
      address: 21
      input_type: input
      device_class: aqi
      unit_of_measurement: ppm
      data_type: int16 #das muss noch verifiziert werden
    - name: "Luftfeuchte Wohnzimmer"
      unique_id: proxon_luftfeuchte_wohnzimmer
      scan_interval: 30
      slave: 41
      address: 22
      input_type: input
      device_class: humidity
      unit_of_measurement: "%"
      data_type: int16 #das muss noch verifiziert werden
    - name: "Lüftungsstufe Ventilator Zuluft"
      unique_id: proxon_lueftungsstufe_ventilator_zuluft
      scan_interval: 30
      slave: 41
      address: 154
      input_type: input
      data_type: int16
    - name: "Betriebsart"
      unique_id: proxon_betriebsart
      scan_interval: 30
      slave: 41
      address: 16
      input_type: holding
      data_type: uint16
    - name: "Soll-Temperatur Wohnzimmer (Zone1)"
      unique_id: proxon_soll_temperatur_wohnzimmer_zone1
      scan_interval: 30
      slave: 41
      address: 70
      input_type: holding
      scale: 0.01
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Soll-Temperatur Büro KG (Zone2)"
      unique_id: proxon_soll_temperatur_buero_kg_zone2
      scan_interval: 30
      slave: 41
      address: 75
      input_type: holding
      scale: 0.01
      precision: 1
      unit_of_measurement: °C
      data_type: int16
    - name: "Soll-Temperatur Wasser"
      unique_id: proxon_soll_temperatur_wasser
      scan_interval: 30
      slave: 41
      address: 2000
      input_type: holding
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16 #das muss noch verifiziert werden
    - name: "Temperatur-Schwelle Heizstab Wasser"
      unique_id: proxon_temperatur_schwelle_heizstab_wasser
      scan_interval: 30
      slave: 41
      address: 2003
      input_type: holding
      scale: 0.1
      precision: 1
      unit_of_measurement: °C
      data_type: int16 #das muss noch verifiziert werden
    - name: "Restzeit Intensivlüftung"
      unique_id: proxon_restzeit_intensivlueftung
      scan_interval: 30
      slave: 41
      address: 133
      input_type: holding
      unit_of_measurement: min
      data_type: uint16
    - name: "Zeit FWT Online"
      unique_id: proxon_zeit_fwt_online
      scan_interval: 30
      slave: 41
      address: 467
      input_type: holding
      unit_of_measurement: std
      data_type: uint16
    - name: "Standzeit FWT Gerätefilter"
      unique_id: proxon_standzeit_fwt_geraetefilter
      scan_interval: 30
      slave: 41
      address: 460
      input_type: holding
      unit_of_measurement: std
      data_type: uint16
    - name: "Nutzzeit FWT Gerätefilter"
      unique_id: proxon_nutzzeit_fwt_geraetefilter
      scan_interval: 30
      slave: 41
      address: 469
      input_type: holding
      unit_of_measurement: std
      data_type: uint16
    - name: "Mitteltemperatur HNBP Keller 1"
      unique_id: proxon_mitteltemperatur_hnbp_keller1
      scan_interval: 30
      slave: 41
      address: 233
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Küche"
      unique_id: proxon_mitteltemperatur_nbp_kueche
      scan_interval: 30
      slave: 41
      address: 234
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Diele"
      unique_id: proxon_mitteltemperatur_nbp_diele
      scan_interval: 30
      slave: 41
      address: 235
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Büro EG"
      unique_id: proxon_mitteltemperatur_nbp_buero_eg
      scan_interval: 30
      slave: 41
      address: 236
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Schlafzimmer"
      unique_id: proxon_mitteltemperatur_nbp_schlafzimmer
      scan_interval: 30
      slave: 41
      address: 237
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Martha"
      unique_id: proxon_mitteltemperatur_nbp_martha
      scan_interval: 30
      slave: 41
      address: 238
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Marlene"
      unique_id: proxon_mitteltemperatur_nbp_marlene
      scan_interval: 30
      slave: 41
      address: 239
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Keller 2"
      unique_id: proxon_mitteltemperatur_nbp_keller2
      scan_interval: 30
      slave: 41
      address: 241
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Mitteltemperatur NBP Keller 3"
      unique_id: proxon_mitteltemperatur_nbp_keller3
      scan_interval: 30
      slave: 41
      address: 242
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur HNBP Keller 1"
      unique_id: proxon_offsettemperatur_hnbp_keller1
      scan_interval: 30
      slave: 41
      address: 213
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Küche"
      unique_id: proxon_offsettemperatur_nbp_kueche
      scan_interval: 30
      slave: 41
      address: 214
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Diele"
      unique_id: proxon_offsettemperatur_nbp_diele
      scan_interval: 30
      slave: 41
      address: 215
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Büro EG"
      unique_id: proxon_offsettemperatur_nbp_buero_eg
      scan_interval: 30
      slave: 41
      address: 216
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Schlafzimmer"
      unique_id: proxon_offsettemperatur_nbp_schlafzimmer
      scan_interval: 30
      slave: 41
      address: 217
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Martha"
      unique_id: proxon_offsettemperatur_nbp_martha
      scan_interval: 30
      slave: 41
      address: 218
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Marlene"
      unique_id: proxon_offsettemperatur_nbp_marlene
      scan_interval: 30
      slave: 41
      address: 219
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Keller 2"
      unique_id: proxon_offsettemperatur_nbp_keller2
      scan_interval: 30
      slave: 41
      address: 221
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
    - name: "Offsettemperatur NBP Keller 3"
      unique_id: proxon_offsettemperatur_nbp_keller3
      scan_interval: 30
      slave: 41
      address: 222
      input_type: holding
      unit_of_measurement: °C
      data_type: int16
```

Die Register und deren Namen sind in dem Beispiel natürlich auf mein Haus ausgelegt, aber ein Großteil bleibt natürlich gleich.

Damit ich die einzelnen Register auch regelkonform schalten konnte habe ich dann in Node-Red noch einige Automationen gebaut, z.B. um die Offset-Temperaturen der Bedienpanels korrekt anzusteuern.

Ich denke im ersten Schritt solltest du aber erstmal Home Assistant mit deiner Proxon verbinden um eine Grundlage zu haben. Alles weitere ist dann irgendwie nur noch Fleißarbeit. Gerne kann ich dir dazu später auch nochmals ein paar Hinweise geben.

Grüße

**Comment by AgentP38** [comment]
Wahnsinnnnnn vielen lieben Dank!!! 

Hast du eine Idee, wie man erkennt welcher Raum welche ID hat?

**Comment by m4dmin** [comment]
Ich habe einfach die ausgegebenen Werte (Temperaturen) mit den Werten aus der Android App verglichen, dann war es bei mir recht schnell eindeutig.

**Comment by sethur277** [comment]
Guten Tag zusammen, da geselle ich mich kurz zur Diskussion. Ich habe deine Beispiel Config auch bei mir als Starthilfe in Home Assistant genutzt und kann auch wunderbar die Temperaturen auslesen sowie die Heizelemente schalten an meinerProxon Anlage. Meine Frage, wie genaue wäre den die Syntax um Werte in die Holding Register zu schreiben? Also zum Beispiel wie kann ich die Solltemperatur für einen Raum setzen? 
Danke für die ausführlichen Infos hier!

**Comment by m4dmin** [comment]
Ich mache mal ein Beispiel, wie ich die Temperatur in einem Zimmer setze.

Erstmal die Grundlagen:

- Für jeden Raum gibt es einen Wert für die Mittel-Temperatur (das stellt die Proxon Anlage irgendwie ein, vermutlich in Zusammengang mit der für die Zone gesetzte Temperatur, diesen Wert lasse ich unangetastet)
- Für jeden Raum gibt es einen Wert für die Offset-Temperatur (dieser Wert gibt die Plus oder Minus Werte Am Wand Panel wieder. Dieser Wert passe ich via Home Assistant an, das spiegelt sich dann auch direkt am Wand Panel wieder)

Um die Aktuell eingestellte Temperatur für einen Raum zu bestimmen muss man als die Summe der Mittel- und Offset-Temperatur addieren. Ich mache das via eines Template Sensors...

Hier ein Beispiel:
```
# Template Konfiguration
template:
  - sensor:
      - name: "Soll Temperatur Küche"
        unique_id: template_soll_temperatur_kueche
        unit_of_measurement: °C
        state: "{{ states.sensor.mitteltemperatur_nbp_kuche.state | int + states.sensor.offsettemperatur_nbp_kuche.state | int }}"
```

Wenn ich nun die Soll-Temperatur in Abhängigkeit zur Mittel-Temperatur ändern möchte, dann mache ich das über die Offset-Temperatur.

Die Home Assistant Automations-Möglichkeiten fand ich ein wenig zu kompliziert und habe daher via Node-Red noch eine Automation gebaut, die bei einer Änderung in der UI, diese auch an Modbus weitergibt.
